feat: 댓글 CRUD 기능 구현
DevVision-B10/DevVision pull request #5
Opened 2024-06-18 11:29 UTC by junghyunwoo02

기능 자체는 다 구현했습니다

2024-06-18 16:21 UTC, munyeol-Yoon requested changes
리뷰드렸습니다. 코멘트 드린부분 수정해주시고, 남은 미구현 사항들 구현되면 Approve 하도록 하겠습니다.

2024-06-18 16:21 UTC, munyeol-Yoon commented on package.json
> +    "uuidv4": "^6.2.13",
사용하지 않는것 같으니 지워주시고, uuid 사용해주세요.

2024-06-18 16:21 UTC, munyeol-Yoon commented on src/pages/Detail.jsx
> +      }
console.error 는 사용자가 알 수 없으니 alert 로 바꾸거나 ux 적으로 사용자가 알 수 있도록 바꿔주세요.

2024-06-18 16:21 UTC, munyeol-Yoon commented on src/pages/Detail/Detail.jsx
> +        </p>
api 데이터로 바꿔주어야 할 것 같습니다.

2024-06-18 16:21 UTC, munyeol-Yoon commented on src/pages/Detail/Detail.jsx
>  `;
컴포넌트에 스타일들이 너무 많습니다. 파일 분할 부탁드리겠습니다.

2024-06-19 00:59 UTC, leeejin reviewed
코멘트 달았습니다!

2024-06-19 00:59 UTC, leeejin commented on src/pages/Detail/Detail.jsx
> +        console.error('댓글 삽입 중 오류 발생:', error);
보통 이런경우는 사용자에게도 에러메시지를 보여줘야해서 alert로 바꾸시는게 좋을것같아요
console.errror => alert로

2024-06-19 00:59 UTC, leeejin commented on src/pages/Detail/Detail.jsx
> +
반복되는 스타일은 GlobalStyle에 선언해두고 최대한 코드를 줄이는게 좋습니다!

2024-06-19 02:48 UTC, junghyunwoo02 commented on package.json
> +    "uuidv4": "^6.2.13",
수정 완료

2024-06-19 02:48 UTC, junghyunwoo02 commented on src/pages/Detail.jsx
> +      }
alert로 사용자가 알 수 있게 변경

2024-06-19 02:48 UTC, junghyunwoo02 commented on src/pages/Detail/Detail.jsx
>  `;
스타일 컴포넌트 분리 완료

2024-06-19 03:20 UTC, junghyunwoo02 commented on src/pages/Detail/Detail.jsx
> +        console.error('댓글 삽입 중 오류 발생:', error);
alert로 사용자가 알 수 있게 변경

2024-06-19 03:21 UTC, junghyunwoo02 commented on src/pages/Detail/Detail.jsx
> +
이거는 제가 반복되는 스타일 파악이 어려워서 기능 구현에 집중하고 해보겠습니다

2024-06-19 10:12 UTC, junghyunwoo02 commented on src/pages/Detail/Detail.jsx
> +        </p>
api 데이터로 변경 완료

2024-06-19 10:17 UTC, leeejin commented on src/App.jsx
>  }
혹시 TanstackQuery를 사용하고싶으시다면 

const queryClient = new QueryClient();
function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  );
}
이 코드로 수정해주시면 됩니다

2024-06-19 10:19 UTC, leeejin commented on src/api/api.js
> +    return response.data.items;
**혹시나 해서 말씀드립니다 !**
console.log는 기능이 돌아가기 위한 확인 목적으로 사용할때 사용하시고 
기능이 문제없이 돌아간다 하면 지워주시는 습관을 기르는 것도 좋을듯합니다

2024-06-19 10:19 UTC, leeejin commented on src/api/api.js
> +    alert('뭔가 잘못된 것 같아요! 데이터를 로드 할 수 없어요. ㅠ.ㅠ');
여기도 마찬가지로 catch 부분은 console.log를 지워주시고 보통 catch 안에는 console.error를 자주 씁니다

2024-06-19 10:20 UTC, leeejin commented on src/pages/Detail/Detail.jsx
> +} from './DetailStyle';
무슨일이  있었던거죠 ㄷㄷ 이건 나중에 확인해봐야겠네요!!

2024-06-19 10:21 UTC, leeejin commented on src/pages/Detail/Detail.jsx
> +
66~71번째 줄은 엘리먼트들이 분포하는 148번째줄 바로 위에 위치하는게 좋습니다
그리고 마찬가지로 72번째줄도 데이터가 잘 오는걸 확인하셨다면 지우시는걸 권장드립니다!

2024-06-19 10:22 UTC, junghyunwoo02 commented on src/api/api.js
> +    return response.data.items;
이런 디테일을 놓쳤군요, 꼼꼼히 봐주셔서 감사합니다.

2024-06-19 10:31 UTC, junghyunwoo02 commented on src/App.jsx
>  }
쿼리 폴더 생성한거 확인하시면 아시겠지만 query 폴더 생성 후 children 프롭으로 내려줬습니다!
방식을 어떻게 할 지는 팀원분들 모두 상의해서 정하는 게 좋을 것 같습니다.

2024-06-19 10:35 UTC, leeejin reviewed
코멘트 달았습니다 !!

2024-06-19 10:35 UTC, leeejin commented on src/pages/Detail/Detail.jsx
> +      console.error('댓글 수정 중 오류 발생:', error);
여기도 댓글 수정을 실패했다는 메시지를 사용자한테 알려주면 좋겠네요

2024-06-19 10:35 UTC, leeejin commented on src/pages/Detail/DetailStyle.jsx
> +
약간 이런 폰트 스타일은 GlobalStyle에 넣는게 좋을것같아요 
저는 font-title (h1 태그)이란 스타일로 넣어놨긴했는데 
h2같은건 sub느낌이니까 font-subTitle 머 이런식으로 다른데서도 쓸수있게 넣는게 좋을듯합니다!

2024-06-19 10:35 UTC, leeejin commented on src/pages/Detail/DetailStyle.jsx
> +
여기도 마찬가지로 6~7번째까지는 지우시고 d-flex-column등의 클래스를 활용해보세요

2024-06-19 10:35 UTC, leeejin commented on src/pages/Detail/DetailStyle.jsx
> +  background-color: transparent;
button 의 기본 스타일이 이미 만들어져 있어 거기서 없는것만 넣어주시면 좋을것같습니다

2024-06-19 10:35 UTC, leeejin commented on src/pages/Detail/DetailStyle.jsx
> +`;
여기도 클래스명 d-flex-column을 사용하시면 좋겠네요

2024-06-19 10:35 UTC, leeejin commented on src/pages/Detail/DetailStyle.jsx
> +  font-family: 'Pretendard Variable';
textarea가 여기서만 사용되는진 잘모르겠지만 184~186번째, 188~190번재 줄까지는 GlobalStyle로 textarea 기본 스타일로 지정해도 좋을것같아요

2024-06-19 10:35 UTC, leeejin commented on src/query/QueryProvider.jsx
> +}
아 여기서  tanstack query를 불러오는군요
tanstack query provider가 app.js에 있어서 이파일은 삭제해주시고 app에다가 옮겨야 할듯 합니다

2024-06-19 10:35 UTC, leeejin commented on src/pages/Detail/Detail.jsx
> +      if (error) {
무슨데이터인지 잘 알아볼 수 있게 Comments로 data이름을 지정한거 아주 좋습니다!

2024-06-19 10:36 UTC, leeejin commented on src/App.jsx
>  }
음 query폴더를 왜 생성한지에 대한 이유가 있을까요 ???
그냥 App.jsx에 3줄만 추가하면 되가지고 폴더 생성을 한 이유가 궁금합니다 !

2024-06-19 10:40 UTC, junghyunwoo02 commented on src/App.jsx
>  }
맞습니다. 처음에는 저도 그렇게 하려고 했는데 문열님이 이렇게 하는 방식도 알려주셔서 따라해봤습니다. 😂

2024-06-19 10:42 UTC, junghyunwoo02 commented on src/pages/Detail/Detail.jsx
> +      console.error('댓글 수정 중 오류 발생:', error);
✅

2024-06-19 14:39 UTC, leeejin approved these changes
ㄱㄱ

2024-06-19 14:39 UTC, leeejin commented on src/App.jsx
>  }
아~ 그렇군용 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 좋아요 !!!

2024-06-19 14:39 UTC, munyeol-Yoon approved these changes
이꾸조

![디버그버그](https://github.com/DevVision-B10/DevVision/assets/50113066/f345b1dd-80a5-4656-b070-2cc26d6bfd1d)

2024-06-19 14:39 UTC, merged