feat: 배너 사진 carousel 및 오타 수정 / 유튜브 api 연동
DevVision-B10/DevVision pull request #7
Opened 2024-06-18 16:09 UTC by eunkyum

2024-06-18 16:27 UTC, munyeol-Yoon requested changes
고생해주셨습니다. 조금만 수정해주세욥!

2024-06-18 16:27 UTC, munyeol-Yoon commented on src/App.jsx
> +    </Router>
기존 dev 코드 pull 받으셔서 객체형식의 라우팅으로 변경해주세요.

2024-06-18 16:27 UTC, munyeol-Yoon commented on src/Layout/Menubar.jsx
>  `;
css 부분 파일 분할 부탁드립니다.

2024-06-18 16:27 UTC, munyeol-Yoon commented on src/Layout/Menubar.jsx
> +      <div style={{ display: 'flex', alignItems: 'center' }}>
inline css 는 지향해주세요. 변경 부탁드립니다.

2024-06-18 16:27 UTC, munyeol-Yoon commented on src/api/api.js
> +  baseURL: 'https://www.googleapis.com/youtube/v3',
이 URL 도 .env 로 처리되면 좋을 것 같아요.

2024-06-18 16:27 UTC, munyeol-Yoon commented on src/main.jsx
> +);
라우터 설정이 App 컴포넌트에 되어있으니 프로바이더들은 가급적 App 컴포넌트에 있으면 좋을 것 같습니다.

2024-06-19 01:07 UTC, leeejin reviewed
저도 코멘트 ㄷ ㅏㄹ았습니다
!

2024-06-19 01:07 UTC, leeejin commented on src/pages/HomePage/HomePage.jsx
> +};
검색쪽은 제가 이어받아서 해보겠습니다 이거 지워주셔도될것같아요

2024-06-19 01:07 UTC, leeejin commented on src/components/HomePage/MainBanner.jsx
> +
이미지 파일은 웬만하면 import에다가 변수처럼 선언하고 넣으시는걸 추천드립니다

import Banner1 from '/src/assets/banner1.png' 
const images = [Banner1,...] 이런식

2024-06-19 10:18 UTC, junghyunwoo02 commented on src/hooks/useCourses.js
> +// import { useState, useEffect } from 'react';
주석은 임시로 해두신거겠죠? 나중에 PR 머지할 때는 주석 제거하고 하면 될 것 같습니다

2024-06-19 10:43 UTC, eunkyum commented on src/hooks/useCourses.js
> +// import { useState, useEffect } from 'react';
앗 넵넵!!

2024-06-19 14:14 UTC, munyeol-Yoon approved these changes
고생하셨습니다 🙇‍♂️

2024-06-19 14:14 UTC, munyeol-Yoon commented on src/components/HomePage/HomePage.jsx
> +    <div style={{ padding: '0 20px' }}>
바꿔주세요

2024-06-19 14:15 UTC, leeejin approved these changes
ㄱㄱ

2024-06-19 14:16 UTC, merged

2024-06-19 15:51 UTC, junghyunwoo02 commented on src/assets/banner1.png
캐러셀 너무 예쁘게 잘 만들어주셨네요!
어떻게 만드셨는지 궁금합니다.

2024-06-19 15:52 UTC, eunkyum commented on src/assets/banner1.png
칭찬 너무 감사해요 😉
어떻게 만들었는지는 비.밀!